# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtFgDR4ekYvMZ6FZsh0l9sN-VXHh4h5I

# Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

"""# **Loading the Dataset**"""

data=pd.read_excel("Online Retail (1).xlsx")

data

"""# Exploratory Data **Analysis**"""

data.head()

data.tail()

data.info()

data.shape

data.describe()

"""# Data **Cleaning**"""

data.duplicated().sum()

data.isnull().sum()

"""

```
كل النسخ المتكرره عايز اشوفها
```

"""

data[data.duplicated(keep=False)].head()

data = data.drop_duplicates()

data.duplicated().sum()

data['InvoiceDate']=pd.to_datetime(data['InvoiceDate'])

data['Year'] = data['InvoiceDate'].dt.year
data['Month'] = data['InvoiceDate'].dt.month
data['Day'] = data['InvoiceDate'].dt.day
data['Hour'] = data['InvoiceDate'].dt.hour

data

data['InvoiceNo'].value_counts()

data = data.loc[
    (data['Quantity'] > 0) &
    (data['UnitPrice'] > 0) &
    (~data['InvoiceNo'].astype(str).str.startswith('C'))
].copy()

data = data[data['InvoiceNo'].astype(str).str.isnumeric()]
data['InvoiceNo'] = data['InvoiceNo'].astype(int)

data.shape

data['InvoiceNo'].astype(str).str.startswith('C').sum()

data.info()

data.isnull().sum()

data = data.dropna(subset=['CustomerID'])

data.isnull().sum()

"""# Feature **Engineering**"""

data['TotalPrice'] = data['Quantity'] * data['UnitPrice']

num_columns=data.select_dtypes(exclude='object').columns
num_columns

"""# Outlier Detection & **Removal**"""

for i in num_columns:
  sns.boxplot(data[i])
  plt.title(i)
  plt.show()

# بس على الأعمدة اللي ليها معنى فعلاً
outlier_cols = ['Quantity', 'UnitPrice', 'TotalPrice']

for col in outlier_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    data = data[(data[col] >= lower) & (data[col] <= upper)]

for i in num_columns:
  sns.boxplot(data[i])
  plt.title(i)
  plt.show()

for i in num_columns:
  sns.histplot(data[i])
  plt.title(i)
  plt.show()

"""# Correlation **Analysis**"""

data.corr(numeric_only=True)

plt.figure(figsize=(10,10))
sns.heatmap(data[num_columns].corr(),annot=True)











"""# Business **Insights**"""

top_product_qty = (
    data.groupby('Description', as_index=False)['Quantity']
    .sum()
    .sort_values('Quantity', ascending=False)
    .head(10)
)
print(top_product_qty)

plt.figure(figsize=(10,6))

plt.barh(top_product_qty['Description'], top_product_qty['Quantity'])

plt.title('Top 10 Products by Quantity Sold')
plt.xlabel('Quantity Sold')
plt.ylabel('Product')

plt.gca().invert_yaxis()  # يخلي الأعلى في الأول

plt.show()

top_product_TotalPrice = (
    data.groupby('Description')['TotalPrice']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_product_TotalPrice

top_product_TotalPrice.plot(figsize=(10,3))
plt.xticks(rotation=90)
plt.title('Top 10 Products by Total Revenue')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.bar(top_product_TotalPrice.index, top_product_TotalPrice.values)

plt.xticks(rotation=90)
plt.title('Top 10 Products by Total Revenue')
plt.xlabel('Product')
plt.ylabel('Total Revenue')

plt.show()

data

"""# RFM Analysis **bold text**"""

snapshot_date = data['InvoiceDate'].max() + pd.Timedelta(days=1)
rfm = data.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalPrice': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']
rfm.head()

best_customer = (
    data.groupby('CustomerID')['TotalPrice']
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

best_customer

top_product = (
    data.groupby('Description')['Quantity']
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

top_product

top_countries = (
    data.groupby('Country')['TotalPrice']
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

top_countries

sales_by_hour = (
    data.groupby('Hour')['TotalPrice']
    .sum()
    .sort_values(ascending=False)
)

sales_by_hour

top_hour = sales_by_hour.head(1)
top_hour

plt.figure(figsize=(10,6))

plt.bar(sales_by_hour.index, sales_by_hour.values)

plt.title('Sales by Hour')
plt.xlabel('Hour')
plt.ylabel('Total Sales')

plt.xticks(range(0,24))

plt.show()

data.hist(bins=15,figsize=(15,10))
plt.show()

data['Month'] = data['InvoiceDate'].dt.month
monthly_sales = data.groupby('Month')['TotalPrice'].sum()
monthly_sales

rfm.describe()

data

"""# KMeans **Clustering**"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(
    rfm[['Recency', 'Frequency', 'Monetary']]
)

ssd = []

for k in range(2, 9):
    kmeans = KMeans(
        n_clusters=k,
        max_iter=50,
        random_state=42
    )
    kmeans.fit(rfm_scaled)
    ssd.append(kmeans.inertia_)

plt.plot(range(2, 9), ssd, marker='o')
plt.axvline(x=3, color='red', linestyle='--', label='Chosen K=3')
plt.legend()
plt.title('Elbow Method - Optimal K')
plt.xlabel('Number of clusters')
plt.ylabel('SSD')
plt.show()

kmeans = KMeans(
    n_clusters=3,   # أو 4 حسب الـ elbow
    max_iter=50,
    random_state=42
)

kmeans.fit(rfm_scaled)
rfm['Cluster_Id'] = kmeans.labels_
rfm.head()
#Cluster 2: VIP / Champions Customers
#Cluster 0: Regular / Potential Loyal Customers
#Cluster 1: Lost / Churned Customers
rfm['Segment'] = rfm['Cluster_Id'].map({
    2: 'VIP / Champions',
    0: 'Regular / Potential Loyal',
    1: 'Lost / Churned'
})
print(rfm['Segment'].value_counts())

"""# Cluster **Analysis**"""

sns.boxplot(x='Cluster_Id', y='Monetary', data=rfm)

sns.boxplot(x='Cluster_Id', y='Frequency', data=rfm)

sns.boxplot(x='Cluster_Id', y='Recency', data=rfm)

rfm['Segment'] = rfm['Cluster_Id'].map({
    2: 'VIP / Champions',
    0: 'Regular / Potential Loyal',
    1: 'Lost / Churned'
})
print(rfm['Segment'].value_counts())

#  قوله يعمل mean على الأعمدة الرقمية بس
cluster_summary = rfm.groupby('Cluster_Id')[['Recency', 'Frequency', 'Monetary']].mean()
cluster_summary

